### ISSUE TITLE
warning about keys in job tables from OpenJobs

### ISSUE THREAD

**Issue by kasumi-1** [semperai/effectiveacceleration.ai#100]
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `cell`. It was passed a child from OpenJobs. See https://reactjs.org/link/warning-keys for more information.

**Comment by jojedev** [comment]
https://github.com/semperai/effectiveacceleration.ai/commit/c9c0dc966e7b1e0d79874fa9f241078410129e7a
https://github.com/semperai/effectiveacceleration.ai/commit/9cd0b64930db11fa8ec9dab8acb0d7aae21a825c
