### ISSUE TITLE
job filter should include arbitrator and maybe even creator as fields

### ISSUE THREAD

**Issue by kasumi-1** [semperai/effectiveacceleration.ai#112]
the arbitrator should default to the arbitration dao address, somewhere we store this to make default on create job page too. 

there is a risk that people post jobs with different arbitrator that will always side with them, so people changing the arbitrator should be let known of this reality.

**Comment by kasumi-1** [comment]
we may as well want to include multiple applicants and so on ?

**Comment by jojedev** [comment]
Now we have multiple applicants, search for arbitrator and search by creator address. Will close it for now, feel free to open it again or create another task :)

![image](https://github.com/user-attachments/assets/7e04a822-2d01-447b-a332-5c1be8be0850)

https://github.com/semperai/effectiveacceleration.ai/commit/6edbc25be7f6a396f215a8d1756966bbb8c54e6d
https://github.com/semperai/effectiveacceleration.ai/commit/07114cdfa97aa853fed4e0f73da9f0ecb80fc29f
https://github.com/semperai/effectiveacceleration.ai/commit/62183af6ed3570733733df01bd539a68eeff3119

**Comment by jojedev** [comment]
This need more styling but I will wait for the design to be ready to fix it
