### ISSUE TITLE
[Bug] 400 Request when setting an empty filter

### ISSUE THREAD

**Issue by AlternateIf** [semperai/effectiveacceleration.ai#123]
1) Go to https://staging.effectiveacceleration.ai/dashboard/open-job-list
2) Filter for 1 Days by increasing the Delivery Time input. Request is fired and succeeds (for me with empty result)
3) now remove the 1 from the input (as a user i would expect to see the previous list again as i have "reset" the filter

Bug:
The request fired by (3) delivers a 400 response with the error
Object { message: "Int cannot represent non-integer value: NaN", extensions: {…} }

Expectation:
No failed request but rather the initial list.

Probable Solution:
Do not send empty form fields with the request

**Comment by jojedev** [comment]
https://github.com/semperai/effectiveacceleration.ai/commit/86a1d07ec4a93943603425890a89fa08e50472e7

**Comment by AlternateIf** [comment]
Thanks 🎉 @jojedev
