### ISSUE TITLE
[Bug] Continue button sometimes disabled when setting arbitrator required to no

### ISSUE THREAD

**Issue by AlternateIf** [semperai/effectiveacceleration.ai#128]
1) go to https://staging.effectiveacceleration.ai/dashboard/post-job
2) add job data
3) do not enter an arbitrator
4) siwtch to arbitrator required no
5) continue button is disabled

can be worked around by setting an arbitrator and the switching to no

**Comment by jojedev** [comment]
Thanks!
https://github.com/semperai/effectiveacceleration.ai/commit/b16470b9a4b8ccee8e5d3d0d9d157649608a0da1
