### ISSUE TITLE
max job time shown on job details does not specify units

### ISSUE THREAD

**Issue by kasumi-1** [semperai/effectiveacceleration.ai#20]

**Comment by jojedev** [comment]
Right now we're not able to store the time units on the contract. I'm asking pat his opinion on this, I tought in a crafty solution like storing the deadline number with a decimal and with the decimal we could know the time unit. 
for ex.
days: 
00.1
weeks: 
00.2
months: 
00.3.
etc

**Comment by kasumi-1** [comment]
we should just use seconds like the contract, and pretty print it, ie convert from 23442 seconds to 2 days, 16 hours

**Comment by jojedev** [comment]
I also added the maxtime on the job details when job is on open state,  this example was succesfully done creating a new job, storing seconds and then pretty printing it on job details.

![image](https://github.com/user-attachments/assets/6ce9cc26-bca7-492d-b489-97dc1bb23e73)


https://github.com/semperai/effectiveacceleration.ai/commit/dd89ac2fcf4cceefbd3a27488757b5344de30e76
