### ISSUE TITLE
dont show zeroaddress on job details when no arbitrator is selected 

### ISSUE THREAD

**Issue by kasumi-1** [semperai/effectiveacceleration.ai#22]

**Comment by jojedev** [comment]
https://github.com/semperai/effectiveacceleration.ai/commit/b46006b6a5974ebeac02a9fed538f8f81f5a9d30

**Comment by jojedev** [comment]
![image](https://github.com/user-attachments/assets/cf4c7dba-7ae2-46fb-a6fc-88dbef36c865)
