### ISSUE TITLE
replace rebecca with applicant name

### ISSUE THREAD

**Issue by kasumi-1** [semperai/effectiveacceleration.ai#28]

**Comment by jojedev** [comment]
How did you found this? the only place rebecca is hard coded rn is on a page that we're not using right now.
![image](https://github.com/user-attachments/assets/bc79fbfe-75be-4504-b1d3-806f2b2be2c1)
http://localhost:3000/dashboard/job/applicants/1

Or at least this is what I think, maybe you're talking of something else or I'm confused
