### ISSUE TITLE
provide stylized button for creating job

### ISSUE THREAD

**Issue by kasumi-1** [semperai/effectiveacceleration.ai#35]
since this is important item in navbar, we should increase its visibility

**Comment by jojedev** [comment]
Here are some ideas: 

1. Simple white border
![image](https://github.com/user-attachments/assets/4467d317-0ca6-4203-86dd-58a7fc262f3c)
2. 1st Complemented gradient with sidebar background: linear-gradient(34deg, rgba(195,141,193,1) 10%,rgba(157,139,227,1) 90%);
![image](https://github.com/user-attachments/assets/9156940d-b6ca-4e98-8f95-f4cfd0dce889)
3. 2nd Complemented gradien with sidebar background:     background: linear-gradient(34deg, rgba(65, 130, 180, 1) 28%, rgba(195, 141, 193, 1) 90%);
![image](https://github.com/user-attachments/assets/a206f8df-8e72-43c5-9bab-9be1a94395a0)
3. Plain bg:  background-color: rgb(65 130 180 / 80%);
![image](https://github.com/user-attachments/assets/af6f5f7c-c314-4fc6-bad8-2f27c7d86473)
