### ISSUE TITLE
provide help text around site explaining how parts work

### ISSUE THREAD

**Issue by kasumi-1** [semperai/effectiveacceleration.ai#41]

**Comment by jojedev** [comment]
I'm thinking about using a icon like this and showing little popups with information. What do you think?
![image](https://github.com/user-attachments/assets/20a882e2-d899-4528-be69-b5abf92b383a)

**Comment by kasumi-1** [comment]
yes that would be helpful :)

**Comment by kasumi-1** [comment]
@jojedev i just created a tooltipbutton component that may be useful for this.

**Comment by jojedev** [comment]
https://github.com/semperai/effectiveacceleration.ai/issues/83

**Comment by kasumi-1** [comment]
for specific places we can add new issues for this
