### ISSUE TITLE
don't show next / previous buttons in paginations if there are not next/previous pages

### ISSUE THREAD

**Issue by kasumi-1** [semperai/effectiveacceleration.ai#44]

**Comment by jojedev** [comment]
Found out that pagination is completely hardcoded
![image](https://github.com/user-attachments/assets/afbc7fc0-69f1-49a7-8acf-68658b653f92)

**Comment by jojedev** [comment]
https://github.com/semperai/effectiveacceleration.ai/issues/48

**Comment by kasumi-1** [comment]
closing this since #48 describes same thing
