### ISSUE TITLE
allow people to browse site without connecting wallet

### ISSUE THREAD

**Issue by kasumi-1** [semperai/effectiveacceleration.ai#45]

**Comment by jojedev** [comment]
I assume you're talking about showing open jobs from /open-job-list.
Made it visible for everyone, for now I'll leave this open just in case.

![image](https://github.com/user-attachments/assets/b6fb87eb-932a-405f-98d4-a413ab88837c)

https://github.com/semperai/effectiveacceleration.ai/commit/aa05c964f278d6e8d3b64f275cd4d2dd51a7fd41
