### ISSUE TITLE
Pagination is completely harcoded

### ISSUE THREAD

**Issue by jojedev** [semperai/effectiveacceleration.ai#48]
Make pagination to work properly taking in consideration quantity of users.

https://staging.effectiveacceleration.ai/dashboard/users?page=2

![image](https://github.com/user-attachments/assets/24428db2-ce16-4c93-9f12-e22b104498d0)

**Comment by kasumi-1** [comment]
6d92df1b5a5cd8154987dcf421d82c71c79b158f
