### ISSUE TITLE
show job being closed / reopened in history on job/:id page

### ISSUE THREAD

**Issue by kasumi-1** [semperai/effectiveacceleration.ai#50]

**Comment by jojedev** [comment]
Added job being closed, but for some reason when you reopen a job it doesn't create a event for it, only for closed ones, if you ask me I can investigate further why reopened jobs doesnt get registered in events history


https://github.com/semperai/effectiveacceleration.ai/commit/0a05fca9d307a883855d791fa7a74fe418e8d2ca

**Comment by kasumi-1** [comment]
isnt it JobEventType.Reopened inside reopenJob in MarketplaceV1.sol ?

any way I just tried and it worked :) maybe some bug fixed in meanwhile, thx

**Comment by jojedev** [comment]
I'm glad it worked
