### ISSUE TITLE
"You accepted the Job." in workerAccepted.tsx should show different text if connected account is owner or worker on job

### ISSUE THREAD

**Issue by kasumi-1** [semperai/effectiveacceleration.ai#52]

**Comment by jojedev** [comment]
![image](https://github.com/user-attachments/assets/828da1bb-1e4b-442c-9626-976e3e88efac)

https://github.com/semperai/effectiveacceleration.ai/commit/3c98132e46d6104ee5c07efda4bae94ab946a77b
