### ISSUE TITLE
if arbitration is active we shouldnt show the "you started a job" pane

### ISSUE THREAD

**Issue by kasumi-1** [semperai/effectiveacceleration.ai#53]
two panes for this looks weird

**Comment by jojedev** [comment]
When arbitration is active I see this:
![image](https://github.com/user-attachments/assets/f971f8cb-e762-48f3-a824-dc9dd159086c)

Could you please provide more info about this issue?

**Comment by kasumi-1** [comment]
![Screenshot 2024-11-26 at 09 54 22](https://github.com/user-attachments/assets/ace15c64-3142-4540-b911-001250bf03e0)

**Comment by jojedev** [comment]
This should have happened before because of the disputed bug where it didn't came back to false. Now it does and this shouldnt happen.
