### ISSUE TITLE
refuse arbitration should pop up a modal informing arbitrator what this entails

### ISSUE THREAD

**Issue by kasumi-1** [semperai/effectiveacceleration.ai#57]
and having button there to do it

**Comment by jojedev** [comment]
This is done, but would like your review on this @kasumi-1 
![image](https://github.com/user-attachments/assets/2e29c92b-b881-429a-abf4-60f6a090684f)

https://github.com/semperai/effectiveacceleration.ai/commit/42f9502cba47f72f06e25a92b4e76c9f76b78a20

**Comment by jojedev** [comment]
Will close this for now, we only need to change the copy
