### ISSUE TITLE
As worker, now the job details are being displaying down left.

### ISSUE THREAD

**Issue by jojedev** [semperai/effectiveacceleration.ai#62]
@kasumi-1 Do you want me to fix it in order to work properly with the chat or this is a bug?

![image](https://github.com/user-attachments/assets/60d26d86-e486-48a7-9e24-ec8c956ae800)

**Comment by kasumi-1** [comment]
please fix it it must be from my refactor and not proper testing :) sorry!

**Comment by kasumi-1** [comment]
i fixed it i think
