### ISSUE TITLE
worker and creator of job is not able to see arbitrators message

### ISSUE THREAD

**Issue by kasumi-1** [semperai/effectiveacceleration.ai#72]
![Screenshot 2024-11-26 at 12 07 39](https://github.com/user-attachments/assets/97d7929d-b61c-41ee-8103-451a4ba93358)

**Comment by jojedev** [comment]
https://github.com/semperai/effectiveacceleration.ai/issues/84

**Comment by jojedev** [comment]
![image](https://github.com/user-attachments/assets/86b78ad7-0c6c-43f5-a123-bf2d6703f4fe)
