### ISSUE TITLE
for mobile support, on jobs page make chatlist and the job info panel slide out like how the sidebar menu does

### ISSUE THREAD

**Issue by kasumi-1** [semperai/effectiveacceleration.ai#73]
we can have some logic around when to show either by default on load.. i think it would be:

Open:
creator - show chat list, hide job details
potential worker - show job details
guest - show details

Taken:
creator - hide job details
worker - hide job details
guest - show details

Closed:

creator - show job details
worker - show job details
guest - show details

**Comment by jojedev** [comment]
https://github.com/semperai/effectiveacceleration.ai/issues/83

**Comment by jojedev** [comment]
Right now in mobile we'll have two options: Show chatlist and show job info. 

Show chatlist (left icon) only appears if you're the owner of a job and job is open.

Show job info (right icon) will always be accesible in mobile for anyone.

![image](https://github.com/user-attachments/assets/bec05a89-f82c-4a85-a680-d6fa5a5d8ee1)
![image](https://github.com/user-attachments/assets/6f5f38ac-8d49-45a4-845a-a0e40d71d5f3)

For now i'll close this task, If you have any observation please feel free to open it again
