### ISSUE TITLE
remove description as requirement for job post

### ISSUE THREAD

**Issue by kasumi-1** [semperai/effectiveacceleration.ai#81]
it isnt really required, and some simple jobs do not need additional context besides title

**Comment by jojedev** [comment]
https://github.com/semperai/effectiveacceleration.ai/commit/2f00f8e431e8ed43fa6635320dd662bd81719057
https://github.com/semperai/effectiveacceleration.ai/commit/8670ee4add7a7e708725d3b3f92f238d537f4a3c
